name: 编译Lean固件
on:
  workflow_dispatch:
    inputs:
      REPO_BRANCH:
        description: '请选择源码分支'
        required: true
        default: 'master'
        type: choice
        options:
          - 'master'
      CONFIG_FILE:
        description: '请选择配置文件'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - 'JDY'
          - 'X64'
          - 'MiCR660X'
          
#  schedule:
#   - cron: 35 18 * * *

jobs:
  build:
    name: 编译 Lean ${{ github.event.inputs.CONFIG_FILE }} 固件
    runs-on: ubuntu-22.04
    
    steps:
    - name: 拉取 Action 代码
      uses: actions/checkout@master
      
    - name: 初始化环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        set +e
        docker rmi `docker images -q`
        sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox* google* dotnet* powershell openjdk* mysql* php*
        sudo -E apt-get update
        sudo -E apt-get -y install autoconf build-essential g++ gawk gcc gettext git libelf-dev libncurses5-dev libtinfo5 make patch python2 python3 qemu-utils time gcc-multilib g++-multilib p7zip-full python3-setuptools libfuse-dev ninja-build unzip file wget rsync subversion
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
        
    - name: 克隆源代码、更新feeds
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
      run: |
        git clone --depth 1 $REPO_URL -b ${{ github.event.inputs.REPO_BRANCH }} openwrt
        cd openwrt
        echo src-git kenzok8 https://github.com/kenzok8/openwrt-packages>>feeds.conf.default
        echo src-git small https://github.com/kenzok8/small>>feeds.conf.default
        ./scripts/feeds update -a && ./scripts/feeds install -a
        
    - name: 加载配置文件、自定义配置
      env:
        CONFIG_FILE: '${{ github.event.inputs.CONFIG_FILE }}.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
        
    - name: 预下载依赖
      working-directory: ./openwrt
      run: |
        make download -j$(nproc) V=S
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 编译固件
      working-directory: ./openwrt
      run: |
        make -j$(nproc) V=S || make -j1 V=s
        
    - name : 上传固件
      uses: actions/upload-artifact@master
      with:
        name: OpenWrt
        path: openwrt/bin
        
